/**
 * @file tpApp1Code.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2026-09-02
 **/

#include "tpApp1Code.hpp"

namespace TpApp1 {

TpApp1Code::TpApp1Code(BlinkyBlocksBlock *host) : BlinkyBlocksBlockCode(host), module(host) {
  // @warning Do not remove block below, as a blockcode with a NULL host might be created
  //  for command line parsing
  if (not host) return;

  // Registers a callback (myBroadcastFunc) to the message of type BROADCAST_MSG_ID
  addMessageEventFunc2(BROADCAST_MSG_ID,
                       std::bind(&TpApp1Code::myBroadcastFunc,
                                 this,
                                 std::placeholders::_1,
                                 std::placeholders::_2)
                       );

  // Registers a callback (myAcknowledgeFunc) to the message of type ACKNOWLEDGE_MSG_ID
  addMessageEventFunc2(ACKNOWLEDGE_MSG_ID,
                       std::bind(&TpApp1Code::myAcknowledgeFunc,
                                 this,
                                 std::placeholders::_1,
                                 std::placeholders::_2)
                       );
}

void TpApp1Code::startup() {
  console << "start " << getId() << "\n";

  if (isLeader) {
    module->setColor(RED);
    currentRound = 1;
    distance = 0;
    parent = nullptr;
    nbWaitedAnswers = sendMessageToAllNeighbors("distance(1,1)",
                                                new MessageOf<pair<int,int>>(BROADCAST_MSG_ID, make_pair(distance + 1, currentRound)),
                                                1000, 100, 0);
  } else {
    currentRound = 0;
  }
}

void TpApp1Code::myBroadcastFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
  MessageOf<pair<int,int>> *msg = static_cast<MessageOf<pair<int,int>>*>(_msg.get());
  pair<int,int> msgData = *msg->getData();

  console << "rec. Flood (" << msgData.first << "," << msgData.second << ") from " << sender->getConnectedBlockId() << "\n";

  if (msgData.second > currentRound || parent == nullptr || msgData.first < distance) {
    isLeader = false;
    distance = msgData.first;
    setColor(distance);
    currentRound = msgData.second;
    parent = sender;

    string str = "distance(";
    str += to_string(distance + 1) + "," + to_string(currentRound) + ")";

    nbWaitedAnswers = sendMessageToAllNeighbors(str.c_str(),
                                                new MessageOf<pair<int,int>>(BROADCAST_MSG_ID, make_pair(distance + 1, currentRound)),
                                                1000, 100, 1, sender);

    if (nbWaitedAnswers == 0) {
      sendMessage("ack2parent", new Message(ACKNOWLEDGE_MSG_ID), parent, 1000, 100);
    }
  } else {
    sendMessage("ack2sender", new Message(ACKNOWLEDGE_MSG_ID), sender, 1000, 100);
  }
}

void TpApp1Code::myAcknowledgeFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
  nbWaitedAnswers--;
  console << "rec. Ack(" << nbWaitedAnswers << ") from " << sender->getConnectedBlockId() << "\n";
  if (nbWaitedAnswers == 0) {
    if (parent == nullptr) {
      console << "Leader " << getId() << " finished gradient propagation for round " << currentRound << "\n";
    } else {
      sendMessage("ack2parent", new Message(ACKNOWLEDGE_MSG_ID), parent, 1000, 100);
    }
  }
}

void TpApp1Code::parseUserBlockElements(TiXmlElement *config) {
  const char *attr = config->Attribute("leader");
  isLeader = (attr ? Simulator::extractBoolFromString(attr) : false);
  if (isLeader) {
    std::cout << getId() << " is leader!" << std::endl;
  }
}

void TpApp1Code::onUserKeyPressed(unsigned char c, int x, int y) {
  switch (c) {
    case 'a':
      std::cout << "key a" << endl;
      break;
    case 'd': break;
  }
}

void TpApp1Code::onTap(int face) {
  std::cout << "Block 'tapped': " << getId() << std::endl;

  isLeader = true;
  distance = 0;
  parent = nullptr;
  currentRound++;

  module->setColor(RED);

  string str = "distance(1," + to_string(currentRound) + ")";
  nbWaitedAnswers = sendMessageToAllNeighbors(str.c_str(),
                                              new MessageOf<pair<int,int>>(BROADCAST_MSG_ID, make_pair(distance + 1, currentRound)),
                                              1000, 100, 0);

  if (nbWaitedAnswers == 0) {
    console << "Single block system: No neighbors to propagate gradient to.\n";
  }
}

} // namespace TpApp1