/**
 * @file tpApp2Code.hpp
 * Generated by VisibleSim BlockCode Generator
 **/

#ifndef tpApp2Code_H_
#define tpApp2Code_H_

#include "robots/blinkyBlocks/blinkyBlocksSimulator.h"
#include "robots/blinkyBlocks/blinkyBlocksWorld.h"
#include "robots/blinkyBlocks/blinkyBlocksBlockCode.h"
#include <utility>
#include <string>

using namespace BlinkyBlocks;

namespace TpApp2 {

static const int MSG_FLOOD_A  = 1001;
static const int MSG_ACK_A    = 1002;
static const int MSG_NOTIFY_B = 1003;
static const int MSG_FLOOD_B  = 1004;
static const int MSG_ACK_B    = 1005;
static const int MSG_NOTIFY_C = 1006;

class TpApp2Code : public BlinkyBlocksBlockCode {
private:
  BlinkyBlocksBlock *module = nullptr;

  bool isA = false;

  // Flood from A to find B
  int distA = -1;
  P2PNetworkInterface *parentA = nullptr;
  int nbWaitedAnswersA = 0;
  int maxDistA = -1;
  int furthestIdA = -1;
  P2PNetworkInterface *bestChildA = nullptr;

  // Flood from B to find C
  int distB = -1;
  P2PNetworkInterface *parentB = nullptr;
  int nbWaitedAnswersB = 0;
  int maxDistB = -1;
  int furthestIdB = -1;
  P2PNetworkInterface *bestChildB = nullptr;

public:
  TpApp2Code(BlinkyBlocksBlock *host);
  ~TpApp2Code() {}

  void startup() override;
  void parseUserBlockElements(TiXmlElement *config) override;

  string onInterfaceDraw() override;

  // Message Handlers
  void onFloodA(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);
  void onAckA(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);
  void onNotifyB(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

  void onFloodB(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);
  void onAckB(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);
  void onNotifyC(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

  static BlockCode *buildNewBlockCode(BuildingBlock *host) {
    return (new TpApp2Code((BlinkyBlocksBlock*)host));
  }
};

} // namespace TpApp2

#endif /* tpApp2Code_H_ */