/**
* @file tpApp2.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2026-09-02
 **/

#include <iostream>
#include "tpApp2Code.hpp"

using namespace std;
using namespace BlinkyBlocks;
using namespace TpApp2;

int main(int argc, char **argv) {
    try {
        createSimulator(argc, argv, TpApp2Code::buildNewBlockCode);
        getSimulator()->printInfo();
        BaseSimulator::getWorld()->printInfo();
        deleteSimulator();
    } catch(std::exception const& e) {
        cerr << "Uncaught exception: " << e.what();
    }

    return 0;
}