/**
 * @file tpApp2Code.cpp
 * Generated by VisibleSim BlockCode Generator
 **/

#include "tpApp2Code.hpp"

BlinkyBlocksBlock *moduleA = nullptr;
BlinkyBlocksBlock *moduleB = nullptr;
BlinkyBlocksBlock *moduleC = nullptr;
BlinkyBlocksBlock *moduleCenter = nullptr;
int distAB = 0, distBC = 0, distBcenter = 0, distCcenter = 0;

namespace TpApp2 {

TpApp2Code::TpApp2Code(BlinkyBlocksBlock *host) : BlinkyBlocksBlockCode(host), module(host) {
  if (not host) return;

  // Register Handlers for Phase 1
  addMessageEventFunc2(MSG_FLOOD_A, std::bind(&TpApp2Code::onFloodA, this, std::placeholders::_1, std::placeholders::_2));
  addMessageEventFunc2(MSG_ACK_A, std::bind(&TpApp2Code::onAckA, this, std::placeholders::_1, std::placeholders::_2));
  addMessageEventFunc2(MSG_NOTIFY_B, std::bind(&TpApp2Code::onNotifyB, this, std::placeholders::_1, std::placeholders::_2));

  // Register Handlers for Phase 2
  addMessageEventFunc2(MSG_FLOOD_B, std::bind(&TpApp2Code::onFloodB, this, std::placeholders::_1, std::placeholders::_2));
  addMessageEventFunc2(MSG_ACK_B, std::bind(&TpApp2Code::onAckB, this, std::placeholders::_1, std::placeholders::_2));
  addMessageEventFunc2(MSG_NOTIFY_C, std::bind(&TpApp2Code::onNotifyC, this, std::placeholders::_1, std::placeholders::_2));
}

void TpApp2Code::parseUserBlockElements(TiXmlElement *config) {
  const char *attr = config->Attribute("isA");
  isA = (attr ? Simulator::extractBoolFromString(attr) : false);
}

string TpApp2Code::onInterfaceDraw() {
  string str = "Press 'r' to run the simulation.";
  if (moduleA != nullptr) {
    str = "A= (" + moduleA->position.to_string() + ")";
  }
  if (moduleB != nullptr) {
    str += "\nB= (" + moduleB->position.to_string() + "), distAB=" + to_string(distAB);
  }
  if (moduleC != nullptr) {
    str += "\nC= (" + moduleC->position.to_string() + "), distBC=" + to_string(distBC);
  }
  if (moduleCenter != nullptr) {
    str += "\nCenter= (" + moduleCenter->position.to_string() + "), dist to B=" +
           to_string(distBcenter) + ", dist to C=" + to_string(distCcenter);
  }
  return str;
}

void TpApp2Code::startup() {
  if (isA) {
    moduleA = module;
    setColor(RED);
    distA = 0;
    maxDistA = 0;
    furthestIdA = getId();

    nbWaitedAnswersA = sendMessageToAllNeighbors("floodA", new MessageOf<int>(MSG_FLOOD_A, distA + 1), 1000, 100, 0);
  }
}

// Find B
void TpApp2Code::onFloodA(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
  MessageOf<int> *msg = static_cast<MessageOf<int>*>(_msg.get());
  int incomingDist = *msg->getData();

  if (distA == -1) {
    distA = incomingDist;
    parentA = sender;
    maxDistA = distA;
    furthestIdA = getId();

    nbWaitedAnswersA = sendMessageToAllNeighbors("floodA", new MessageOf<int>(MSG_FLOOD_A, distA + 1), 1000, 100, 1, sender);

    // If leaf node, reply immediately
    if (nbWaitedAnswersA == 0) {
      sendMessage("ackA", new MessageOf<pair<int,int>>(MSG_ACK_A, make_pair(maxDistA, furthestIdA)), sender, 1000, 100);
    }
  } else {
    // Already visited, send dummy ACK back
    sendMessage("dummyAckA", new MessageOf<pair<int,int>>(MSG_ACK_A, make_pair(-1, -1)), sender, 1000, 100);
  }
}

void TpApp2Code::onAckA(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
  MessageOf<pair<int,int>> *msg = static_cast<MessageOf<pair<int,int>>*>(_msg.get());
  pair<int,int> data = *msg->getData();

  nbWaitedAnswersA--;

  // Track the furthest node reporting back
  if (data.first > maxDistA) {
    maxDistA = data.first;
    furthestIdA = data.second;
    bestChildA = sender;
  }

  // Once all neighbors have reported
  if (nbWaitedAnswersA == 0) {
    if (isA) {
      distAB = maxDistA;
      // Tell the furthest node it is B
      sendMessage("notifyB", new Message(MSG_NOTIFY_B), bestChildA, 1000, 100);
    } else {
      // Pass the max distance up the spanning tree to parent A
      sendMessage("ackA", new MessageOf<pair<int,int>>(MSG_ACK_A, make_pair(maxDistA, furthestIdA)), parentA, 1000, 100);
    }
  }
}

void TpApp2Code::onNotifyB(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
  if (bestChildA != nullptr) {
    // Route the notification further down the path
    sendMessage("notifyB", new Message(MSG_NOTIFY_B), bestChildA, 1000, 100);
  } else {
    // End of the line: I am B
    moduleB = module;
    setColor(YELLOW);
    distB = 0;
    maxDistB = 0;
    furthestIdB = getId();

    // Initiate Phase 2 Flood
    nbWaitedAnswersB = sendMessageToAllNeighbors("floodB", new MessageOf<int>(MSG_FLOOD_B, distB + 1), 1000, 100, 0);
  }
}

// Find C and locate Center
void TpApp2Code::onFloodB(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
  MessageOf<int> *msg = static_cast<MessageOf<int>*>(_msg.get());
  int incomingDist = *msg->getData();

  if (distB == -1) {
    distB = incomingDist;
    parentB = sender;
    maxDistB = distB;
    furthestIdB = getId();

    nbWaitedAnswersB = sendMessageToAllNeighbors("floodB", new MessageOf<int>(MSG_FLOOD_B, distB + 1), 1000, 100, 1, sender);

    if (nbWaitedAnswersB == 0) {
      sendMessage("ackB", new MessageOf<pair<int,int>>(MSG_ACK_B, make_pair(maxDistB, furthestIdB)), sender, 1000, 100);
    }
  } else {
    sendMessage("dummyAckB", new MessageOf<pair<int,int>>(MSG_ACK_B, make_pair(-1, -1)), sender, 1000, 100);
  }
}

void TpApp2Code::onAckB(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
  MessageOf<pair<int,int>> *msg = static_cast<MessageOf<pair<int,int>>*>(_msg.get());
  pair<int,int> data = *msg->getData();

  nbWaitedAnswersB--;

  if (data.first > maxDistB) {
    maxDistB = data.first;
    furthestIdB = data.second;
    bestChildB = sender; // The routing path toward C
  }

  if (nbWaitedAnswersB == 0) {
    if (distB == 0) { // I am B
      distBC = maxDistB;
      int targetCenterDist = distBC / 2; // Midpoint calculation

      // Send message to C, marking the center along the way
      sendMessage("notifyC", new MessageOf<pair<int,int>>(MSG_NOTIFY_C, make_pair(targetCenterDist, 0)), bestChildB, 1000, 100);
    } else {
      sendMessage("ackB", new MessageOf<pair<int,int>>(MSG_ACK_B, make_pair(maxDistB, furthestIdB)), parentB, 1000, 100);
    }
  }
}

void TpApp2Code::onNotifyC(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender) {
  MessageOf<pair<int,int>> *msg = static_cast<MessageOf<pair<int,int>>*>(_msg.get());
  pair<int,int> data = *msg->getData();

  int targetCenterDist = data.first;
  int currentDist = data.second + 1; // Distance from B

  // If this node is at the midpoint, elect it as Center
  if (currentDist == targetCenterDist) {
    moduleCenter = module;
    setColor(BROWN);
    distBcenter = currentDist;
    distCcenter = distBC - currentDist;
  }

  // Continue forwarding to C
  if (bestChildB != nullptr) {
    sendMessage("notifyC", new MessageOf<pair<int,int>>(MSG_NOTIFY_C, make_pair(targetCenterDist, currentDist)), bestChildB, 1000, 100);
  } else {
    // End of the line: I am C
    moduleC = module;
    setColor(BLUE);
  }
}

} // namespace TpApp2